- name: restart kubelet
  service: 
    name: kubelet 
    state: restarted 
    daemon_reload: yes

- name: docker status
  service: 
    name: docker 
    state: started

- name: ufw reloaded
  service: 
    name: ufw 
    state: stopped