- name: Install longhorn
  command: kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

- name: generating auth file
  command: USER=admin PASSWORD=admin echo "${USER}:$(openssl passwd -stdin -apr1 <<< ${PASSWORD})" >> auth

- name: Uploading auth to kube secret
  command: kubectl -n longhorn-system create secret generic basic-auth --from-file=auth

- name: Uploading longhorn ingress
  copy:
    src: yaml/longhorn/ingress.yml
    dest: /tmp/ingress.yml

- name: apply ingress
  command: kubectl -n longhorn-system apply -f /tmp/ingress.yml