- name: Copy the join command to server location
  copy:
    remote_src: no
    src: join-command
    dest: /tmp/join-command.sh
    mode: 0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
